/**
 * Copyright (C) 2014-2016 Emerald Icemoon (emerald.icemoon@gmail.com)
 * 
 * License: http://www.gnu.org/licenses/gpl.html GPL version 3 or higher
 */
package org.icelib;

public enum AttachmentPoint {
	// Others
	NAMEPLATE, LEFT_HAND2, LEFT_HAND_WEAPONS, LEFT_HAND_SHIELD, RIGHT_HAND_ARROW, RIGHT_HAND_STAFF, LEFT_ARM, LEFT_FOREARM_WEAPONS, RIGHT_ARM, CTF, BACK_ARROWS, BACK_1_2HSWORDS, BACK_1_SWORDS, BACK_1_STAFFS, BACK_2_STAFFS, BACK_2_BOWS, BACK_2_2HSWORDS, BACK_2_SWORDS, BACK_5_SPECIAL1, BACK_5_SPECIAL2, BACK_6, BACK_2HSWORD_EQUIP, BACK_POLE_EQUIP, BACK_AXEMACE_EQUIP, CHEST, CHEST2, CHEST3, SPELL_TARGET, SPELL_TARGET_HEAD, SPELL_SYMBOLE, SPELL_ORIGIN, DAZE_STUN, CENTER_HIP, LEFT_HIP_SWORDS, RIGHT_HIP_SWORDS, LEFT_HIP_WANDS, RIGHT_HIP_WANDS, LEFT_HIP_AXES, RIGHT_HIP_AXES, LEFT_HIP_CLAWS, RIGHT_HIP_CLAWS, LEFT_HIP_DAGGERS, RIGHT_HIP_DAGGERS, LEFT_HIP_KATARS, RIGHT_HIP_KATARS, HEAD_PARTICLES, RIGHT_FOOT, LEFT_FOOT, CRAB_SHELL, BASE, LEFT_ELBOW, RIGHT_ELBOW,

	// Defaults ones
	BACK_1, BACK_2, BACK_3, BACK_4, BACK_5, BACK_SHEATHE, HELMET, LEFT_HAND, LEFT_HIP, LEFT_SHOULDER, RIGHT_HAND, RIGHT_HAND2, RIGHT_HAND_WEAPONS, RIGHT_HIP, RIGHT_SHOULDER,
	//
	HEAD, HEAD2, BUNNYEARS, FULL_HELMET, POT, LEFT_EAR, RIGHT_EAR, TAIL, HAT, LEFT_CALF, RIGHT_CALF, LEFT_FOREARM, RIGHT_FOREARM, BACK_PACK, LEFT_EARRING, RIGHT_EARRING, CAPE, HORDE_ATTACKER, HORDE_ATTACKER2, HORDE_CASTER, HORDE_BACK, BASKET;

	public EquipType toEquipType() {
		switch (this) {
		case HELMET:
		case HAT:
			return EquipType.HEAD;
		case LEFT_SHOULDER:
		case RIGHT_SHOULDER:
			return EquipType.SHOULDERS;
		case LEFT_HAND:
		case RIGHT_HAND:
			// Meh. Bit simplistic but it's only for auto item creation
			return EquipType.WEAPON_1H;
		case LEFT_CALF:
		case RIGHT_CALF:
			return EquipType.LEGS;
		case LEFT_FOREARM:
		case RIGHT_FOREARM:
			return EquipType.ARMS;
		case BACK_PACK:
			return EquipType.BELT;
		}
		throw new IllegalArgumentException("Can't convert attachment point " + this + " to equip type.");
	}
}
